# Generated by Django 5.1.2 on 2026-03-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_confirmed_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
    ]
