# Generated by Django 5.1.2 on 2026-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
