# Generated by Django 5.1.2 on 2026-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooter_rate_per_km', models.FloatField(default=5)),
                ('rickshaw_rate_per_km', models.FloatField(default=8)),
                ('tempo_rate_per_km', models.FloatField(default=12)),
                ('scooter_weight_limit', models.IntegerField(default=25)),
                ('rickshaw_weight_limit', models.IntegerField(default=100)),
                ('minimum_delivery_charge', models.FloatField(default=25)),
            ],
        ),
    ]
