# Generated by Django 5.1.2 on 2026-05-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_deliverysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysetting',
            name='delivery_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverysetting',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverysetting',
            name='vehicle_type',
            field=models.CharField(default='Scooter', max_length=20),
        ),
    ]
