# Generated by Django 5.1.2 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_deliverysetting_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysetting',
            name='vehicle_type',
            field=models.CharField(default='Scooter', max_length=50),
        ),
    ]
