# Generated by Django 5.1.2 on 2026-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_deliverysetting_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.CharField(default='Scooter', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
