# Generated by Django 5.1.2 on 2026-05-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_delivery_charge_order_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
